In [313]:
from gensim.models import Word2Vec
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np
import pandas as pd

In [314]:
df = pd.read_csv('./IndianFoodDatasetCSV.csv')
df['TranslatedRecipeName'] = df['TranslatedRecipeName'].str.replace(r'\(Recipe\)|Recipe', '', regex=True)
df.head()


Srno                                         RecipeName  \
0     1                               Masala Karela Recipe   
1     2  टमाटर पुलियोगरे रेसिपी - Spicy Tomato Rice (Re...   
2     3  Ragi Semiya Upma Recipe - Ragi Millet Vermicel...   
3     4  Gongura Chicken Curry Recipe - Andhra Style Go...   
4     5  आंध्रा स्टाइल आलम पचड़ी रेसिपी - Adrak Chutney ...   

                                TranslatedRecipeName  \
0                                     Masala Karela    
1                                 Spicy Tomato Rice    
2  Ragi Semiya Upma  - Ragi Millet Vermicelli Bre...   
3  Gongura Chicken Curry  - Andhra Style Gongura ...   
4        Andhra Style Alam Pachadi  - Adrak Chutney    

                                         Ingredients  \
0  6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...   
1  2-1/2 कप चावल - पका ले,3 टमाटर,3 छोटा चमच्च बी...   
2  1-1/2 cups Rice Vermicelli Noodles (Thin),1 On...   
3  500 grams Chicken,2 Onion - chopped,1 Tomato -...   
4  1 बड़ा चमच्च चना दाल,1 बड़ा चमच्च सफ़ेद उरद दाल,2...   

                               TranslatedIngredients  PrepTimeInMins  \
0  6 Karela (Bitter Gourd/ Pavakkai) - deseeded,S...              15   
1  2-1 / 2 cups rice - cooked, 3 tomatoes, 3 teas...               5   
2  1-1/2 cups Rice Vermicelli Noodles (Thin),1 On...              20   
3  500 grams Chicken,2 Onion - chopped,1 Tomato -...              15   
4  1 tablespoon chana dal, 1 tablespoon white ura...              10   

   CookTimeInMins  TotalTimeInMins  Servings               Cuisine  \
0              30               45         6                Indian   
1              10               15         3  South Indian Recipes   
2              30               50         4  South Indian Recipes   
3              30               45         4                Andhra   
4              20               30         4                Andhra   

                   Course                     Diet  \
0               Side Dish        Diabetic Friendly   
1             Main Course               Vegetarian   
2  South Indian Breakfast  High Protein Vegetarian   
3                   Lunch           Non Vegeterian   
4  South Indian Breakfast               Vegetarian   

                                        Instructions  \
0  To begin making the Masala Karela Recipe,de-se...   
1  टमाटर पुलियोगरे बनाने के लिए सबसे पहले टमाटर क...   
2  To begin making the Ragi Vermicelli Recipe, fi...   
3  To begin making Gongura Chicken Curry Recipe f...   
4  आंध्रा स्टाइल आलम पचड़ी बनाने के लिए सबसे पहले ...   

                              TranslatedInstructions  \
0  To begin making the Masala Karela Recipe,de-se...   
1  To make tomato puliogere, first cut the tomato...   
2  To begin making the Ragi Vermicelli Recipe, fi...   
3  To begin making Gongura Chicken Curry Recipe f...   
4  To make Andhra Style Alam Pachadi, first heat ...   

                                                 URL  
0  https://www.archanaskitchen.com/masala-karela-...  
1  http://www.archanaskitchen.com/spicy-tomato-ri...  
2  http://www.archanaskitchen.com/ragi-vermicelli...  
3  http://www.archanaskitchen.com/gongura-chicken...  
4  https://www.archanaskitchen.com/andhra-style-a...

In [315]:
df.columns

Index(['Srno', 'RecipeName', 'TranslatedRecipeName', 'Ingredients',
       'TranslatedIngredients', 'PrepTimeInMins', 'CookTimeInMins',
       'TotalTimeInMins', 'Servings', 'Cuisine', 'Course', 'Diet',
       'Instructions', 'TranslatedInstructions', 'URL'],
      dtype='object')

In [316]:
df.drop(columns=['RecipeName','PrepTimeInMins', 'CookTimeInMins',
       'TotalTimeInMins', 'Servings','Course', 'Diet',
       'Instructions', 'TranslatedInstructions', 'URL','Ingredients', 'TranslatedIngredients',],inplace=True)
df.columns

Index(['Srno', 'TranslatedRecipeName', 'Cuisine'], dtype='object')

In [317]:
df.head()

Srno                               TranslatedRecipeName  \
0     1                                     Masala Karela    
1     2                                 Spicy Tomato Rice    
2     3  Ragi Semiya Upma  - Ragi Millet Vermicelli Bre...   
3     4  Gongura Chicken Curry  - Andhra Style Gongura ...   
4     5        Andhra Style Alam Pachadi  - Adrak Chutney    

                Cuisine  
0                Indian  
1  South Indian Recipes  
2  South Indian Recipes  
3                Andhra  
4                Andhra

In [318]:
import ssl
import nltk
ssl._create_default_https_context = ssl._create_unverified_context
nltk.download('stopwords')
from nltk.corpus import stopwords
import string
stop_words = stopwords.words("english")
stemming = nltk.stem.PorterStemmer()

[nltk_data] Error loading stopwords: <urlopen error [Errno 8] nodename
[nltk_data]     nor servname provided, or not known>


In [319]:
string.punctuation.lower()

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [320]:
stemming.stem("playing")

'play'

In [321]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [322]:
def word_token(sentence):
    sentence = str(sentence)
    cleaned_sentence_token = []
    for punc in string.punctuation:
        sentence = str(sentence).replace(punc,"")

    for word in sentence.lower().split():
        if word and word not in stop_words:
            cleaned_sentence_token.append( stemming.stem(word))
    return cleaned_sentence_token
            
    

In [323]:
result = [word_token(sentence) for sentence in df['TranslatedRecipeName'][:2]]
result

[['masala', 'karela'], ['spici', 'tomato', 'rice']]

In [324]:
for sentence in df['TranslatedRecipeName'][:2]:
    print(sentence)

Masala Karela 
Spicy Tomato Rice 


In [325]:
new_df = df['TranslatedRecipeName'].apply(word_token)
new_df.head()


0                                     [masala, karela]
1                                [spici, tomato, rice]
2    [ragi, semiya, upma, ragi, millet, vermicelli,...
3    [gongura, chicken, curri, andhra, style, gongu...
4       [andhra, style, alam, pachadi, adrak, chutney]
Name: TranslatedRecipeName, dtype: object

In [326]:
w2vRecipeEmbed	= Word2Vec(new_df,epochs=10,min_count=1,window=5)
w2vRecipeEmbed

In [327]:
w2vRecipeEmbed.wv

In [328]:
w2vRecipeEmbed.wv['curri']

array([-0.2538148 ,  0.414344  ,  0.16851929,  0.13046764, -0.00310489,
       -0.94888484,  0.35890457,  0.9257737 , -0.49971604, -0.43284556,
       -0.09964227, -0.67973995, -0.01403412,  0.22997132,  0.16865729,
       -0.32677418,  0.01142792, -0.6446392 , -0.09856954, -0.9936678 ,
        0.36080164,  0.09008413,  0.23480237, -0.29961318, -0.15499198,
        0.15236765, -0.4944135 , -0.24225014, -0.41034907,  0.03008005,
        0.4696368 ,  0.12352413,  0.23553969, -0.28684232, -0.07101279,
        0.619749  ,  0.06039367, -0.4981484 , -0.22224927, -1.0367997 ,
        0.00113252, -0.4758973 , -0.1883174 , -0.03008251,  0.50642985,
       -0.1415178 , -0.46292576,  0.01573564,  0.32660732,  0.21907318,
        0.27147678, -0.2576011 , -0.02711426, -0.15482211, -0.2738988 ,
        0.05784546,  0.20933378,  0.06093788, -0.56467205,  0.2925824 ,
        0.10765498,  0.04427896, -0.05795031, -0.21284308, -0.5717857 ,
        0.53890127,  0.12979579,  0.46876895, -0.507403  ,  0.80

In [329]:
wordembeddings = {key : w2vRecipeEmbed.wv[key] for key in w2vRecipeEmbed.wv.index_to_key }
wordembeddings

{'style': array([-0.29847986,  0.41165668,  0.18382783,  0.17647547, -0.10773314,
        -1.0506005 ,  0.4072447 ,  0.9901603 , -0.5437142 , -0.43617472,
        -0.06648772, -0.66013026, -0.03249628,  0.2912633 ,  0.17558444,
        -0.37105405, -0.04080826, -0.7157976 , -0.18516527, -1.0636244 ,
         0.41176057,  0.11440783,  0.28519377, -0.30619985, -0.12438761,
         0.15558161, -0.565809  , -0.23293874, -0.5161483 , -0.00163435,
         0.4201975 ,  0.14709698,  0.30311227, -0.33870968, -0.08003052,
         0.6368963 ,  0.11181061, -0.5848065 , -0.27370074, -1.122265  ,
        -0.03220097, -0.48855433, -0.25129285, -0.12703177,  0.57475203,
        -0.17015482, -0.5482877 ,  0.10039643,  0.41819072,  0.28416106,
         0.24250308, -0.23862818, -0.01108398, -0.21758108, -0.21522662,
        -0.02175966,  0.14784575,  0.03770272, -0.5968535 ,  0.3353683 ,
         0.15841454,  0.036765  , -0.13008289, -0.30580908, -0.5805988 ,
         0.62292814,  0.10516163,  0.58724

In [330]:
tfidf = TfidfVectorizer(min_df = 5,tokenizer=word_token)
vector = tfidf.fit_transform(df['TranslatedRecipeName'])


/Users/adityaanand/Desktop/Desktop/DataScience/new_env/lib/python3.11/site-packages/sklearn/feature_extraction/text.py:521: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [331]:
len(wordembeddings)

3775

In [332]:
vector.shape

(6871, 906)

Combining both embedding and vector from tfidf

In [333]:
[np.mean([w2vRecipeEmbed.wv[word] for word in word_token(sentence)],axis=0) for sentence in df['TranslatedRecipeName'][:2]   ]

[array([-1.51949167e-01,  2.78808415e-01,  8.02025199e-02,  9.60947052e-02,
        -1.15587236e-03, -5.67514122e-01,  2.47597992e-01,  5.53143263e-01,
        -2.88521826e-01, -2.32249215e-01, -7.01840669e-02, -4.22437102e-01,
        -1.20755937e-03,  7.09830746e-02,  1.05328023e-01, -2.37826675e-01,
        -3.70238209e-04, -4.27050650e-01, -3.36167105e-02, -6.22848749e-01,
         2.06136346e-01,  6.89758435e-02,  1.56204283e-01, -1.94912642e-01,
        -1.10151768e-01,  8.04359540e-02, -2.77012229e-01, -1.94870234e-01,
        -2.75860339e-01, -3.01860571e-02,  3.06059688e-01,  1.23063639e-01,
         1.98285356e-01, -1.18805721e-01, -7.30268061e-02,  3.95939767e-01,
         7.50485575e-03, -3.35941255e-01, -1.63650542e-01, -6.57421172e-01,
         7.06720632e-04, -3.03653836e-01, -4.72663678e-02,  1.27713596e-02,
         3.17569077e-01, -1.14424795e-01, -2.79303312e-01,  1.09608993e-02,
         2.15337902e-01,  1.14895180e-01,  1.79293454e-01, -1.56768814e-01,
        -2.8

In [334]:
np.array([np.mean([w2vRecipeEmbed.wv[word] for word in word_token(sentence)],axis=0) for sentence in df['TranslatedRecipeName'][:2]   ]).shape

(2, 100)

In [335]:
[y for x in range(1,11) if x%2==0 for y in range(1) ]

[0, 0, 0, 0, 0]

In [336]:
mean_embedding = [
    np.mean([w2vRecipeEmbed.wv[ word] for word in word_token(sentence)],axis=0)
    for sentence in df['TranslatedRecipeName']
    ]
# np.array(mean_embedding)
mean_embedding

[array([-1.51949167e-01,  2.78808415e-01,  8.02025199e-02,  9.60947052e-02,
        -1.15587236e-03, -5.67514122e-01,  2.47597992e-01,  5.53143263e-01,
        -2.88521826e-01, -2.32249215e-01, -7.01840669e-02, -4.22437102e-01,
        -1.20755937e-03,  7.09830746e-02,  1.05328023e-01, -2.37826675e-01,
        -3.70238209e-04, -4.27050650e-01, -3.36167105e-02, -6.22848749e-01,
         2.06136346e-01,  6.89758435e-02,  1.56204283e-01, -1.94912642e-01,
        -1.10151768e-01,  8.04359540e-02, -2.77012229e-01, -1.94870234e-01,
        -2.75860339e-01, -3.01860571e-02,  3.06059688e-01,  1.23063639e-01,
         1.98285356e-01, -1.18805721e-01, -7.30268061e-02,  3.95939767e-01,
         7.50485575e-03, -3.35941255e-01, -1.63650542e-01, -6.57421172e-01,
         7.06720632e-04, -3.03653836e-01, -4.72663678e-02,  1.27713596e-02,
         3.17569077e-01, -1.14424795e-01, -2.79303312e-01,  1.09608993e-02,
         2.15337902e-01,  1.14895180e-01,  1.79293454e-01, -1.56768814e-01,
        -2.8

In [412]:
tfidf = TfidfVectorizer(tokenizer=word_token)
vectorizer = tfidf.fit_transform(df['TranslatedRecipeName'])


/Users/adityaanand/Desktop/Desktop/DataScience/new_env/lib/python3.11/site-packages/sklearn/feature_extraction/text.py:521: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


In [413]:
vectorizer.shape

(6871, 3775)

In [414]:
tfidf.get_feature_names_out()

array(['10', '15', '3', ..., 'रोटी', '–', '｜'], dtype=object)

concatinating embedding and vectors

In [415]:
combined_embeddig = np.concatenate([np.array(mean_embedding),vectorizer.toarray()], axis=1)

In [416]:
combined_embeddig

array([[-0.15194917,  0.27880841,  0.08020252, ...,  0.        ,
         0.        ,  0.        ],
       [-0.23946662,  0.34988102,  0.10734203, ...,  0.        ,
         0.        ,  0.        ],
       [-0.1922469 ,  0.22843497,  0.05655505, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.13779837,  0.23169422,  0.07269619, ...,  0.        ,
         0.        ,  0.        ],
       [-0.19285776,  0.27114794,  0.09385526, ...,  0.        ,
         0.        ,  0.        ],
       [-0.15960816,  0.24103804,  0.05946383, ...,  0.        ,
         0.        ,  0.        ]])

In [417]:
combined_embeddig.shape

(6871, 7550)

### Generating user query

In [418]:
user_query = pd.DataFrame({'query':["Masala Karela Recipe"]})
user_query


query
0  Masala Karela Recipe

In [513]:
user_query = pd.DataFrame({'query':["spicy chicken in chinese style"]})
user_query


query
0  spicy chicken in chinese style

In [535]:
user_vector = tfidf.transform(user_query['query'])
user_vector

<1x3775 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [536]:
tfidf.get_feature_names_out()

array(['10', '15', '3', ..., 'रोटी', '–', '｜'], dtype=object)

In [537]:
user_vector.shape

(1, 3775)

In [423]:
difference = combined_embeddig.shape[1]-user_vector.shape[1]
difference

3775

In [424]:
new_user_vector = np.pad(user_vector.toarray(),pad_width=((0,0),(0,difference)),constant_values=0)

In [425]:
from sklearn.metrics.pairwise import cosine_similarity


In [426]:
similarity_score = cosine_similarity(new_user_vector,combined_embeddig)
similarity_score

array([[0., 0., 0., ..., 0., 0., 0.]])

In [427]:
similarity_score[0].argsort()[::-1][:10]

array([6870, 2280, 2282, 2283, 2284, 2285, 2286, 2287, 2288, 2289])

In [428]:
df.iloc[similarity_score[0].argsort()[::-1][:10]]['TranslatedRecipeName'].tolist()

[' Navrang Dal ',
 'Crispy Corn And Bell Peppers Chaat ',
 'Gujarati Badshahi Pulao  - A Rich Preparation Of Rice, Vegetables, Nuts And Spices',
 'Homemade Sev  - Gram Flour Vermicelli Snack',
 ' Brinjal Capsicum Sabji ( In Hindi)',
 'Masala French Toast ',
 'Raw Banana Thoran ',
 'Hunan Style Smacked Cucumber Pickles ',
 'Creamy Kulfi Kebab  With Tandoori Mayo ',
 'Spinach Sun Dried Tomato Pasta ']

# calculating cosine similarity with only w2v embedding

In [429]:
user_vector

<1x3775 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [430]:
difference = user_vector.shape[1]-np.array(mean_embedding).shape[1]
difference

0

In [431]:
user_vector.shape

(1, 3775)

In [432]:
mean_embedding = np.array(mean_embedding)

In [433]:
np.array(mean_embedding).shape

(6871, 3775)

In [434]:
mean_embedding = np.pad(mean_embedding,pad_width=((0,0,),(0,difference)),constant_values=0)

In [435]:
mean_embedding.shape

(6871, 3775)

In [436]:
similarity_score = cosine_similarity(user_vector,mean_embedding)
similarity_score

array([[0., 0., 0., ..., 0., 0., 0.]])

In [437]:
similarity_score[0].argsort()[::-1][:10]

array([6870, 2280, 2282, 2283, 2284, 2285, 2286, 2287, 2288, 2289])

In [438]:
df.iloc[similarity_score[0].argsort()[::-1][:10]]['TranslatedRecipeName'].tolist()


[' Navrang Dal ',
 'Crispy Corn And Bell Peppers Chaat ',
 'Gujarati Badshahi Pulao  - A Rich Preparation Of Rice, Vegetables, Nuts And Spices',
 'Homemade Sev  - Gram Flour Vermicelli Snack',
 ' Brinjal Capsicum Sabji ( In Hindi)',
 'Masala French Toast ',
 'Raw Banana Thoran ',
 'Hunan Style Smacked Cucumber Pickles ',
 'Creamy Kulfi Kebab  With Tandoori Mayo ',
 'Spinach Sun Dried Tomato Pasta ']

Checking similarioty with tfidf vector

In [439]:
difference = user_vector.shape[1]-vectorizer.toarray().shape[1]
difference

0

In [440]:
# vectorizer = user_vector.toarray()
vectorizer

<6871x3775 sparse matrix of type '<class 'numpy.float64'>'
	with 32774 stored elements in Compressed Sparse Row format>

In [441]:
similarity_score = cosine_similarity(user_vector,vectorizer)
similarity_score

array([[0.        , 0.26757459, 0.        , ..., 0.        , 0.17586975,
        0.        ]])

In [442]:
similarity_score[0].argsort()[::-1][:10]

array([1713, 4140, 4017, 4909, 3900, 4327, 2332, 4818, 1756,  133])

In [443]:
df.iloc[similarity_score[0].argsort()[::-1][:10]]['TranslatedRecipeName'].tolist()

[' Chinese Chicken Fried Rice ',
 'Chilli Chicken  - Delicious Indian Style Chinese Chicken',
 'Chinese Style Green Beans ',
 'Chinese Chicken Sweet Corn Soup ',
 'Chinese Dragon Chicken With Vegetables ',
 'Spicy Pepper Chicken ',
 'Chinese Style Sweet And Spicy Broccoli Stir Fry With Sausage ',
 ' Baked Chinese Potato ',
 'Pan Fried Chinese Chilli Chicken recipe',
 'Indo Chinese Crispy Chicken Chilli ']

In [388]:
tfidf.get_feature_names_out()

array(['10', '15', '3', ..., 'रोटी', '–', '｜'], dtype=object)

## Generating user combined vector embedding space

In [ ]:
# [ np.mean([w2vRecipeEmbed.wv[word]   for word in word_token(sentence) if word in w2vRecipeEmbed.wv ] , axis=0)
 
#  for sentence in user_query]


[np.mean([w2vRecipeEmbed.wv[word] for word in word_token(ingredient_list) if word in w2vRecipeEmbed.wv] or [np.zeros(100)], axis=0) 
for ingredient_list in user_query]

/Users/adityaanand/Desktop/Desktop/DataScience/new_env/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/adityaanand/Desktop/Desktop/DataScience/new_env/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


[nan]

In [463]:
[
    [w2vRecipeEmbed.wv[word] for word in word_token(ingredient_list) if word in w2vRecipeEmbed.wv]
    for ingredient_list in user_query['query']
]


[[array([-2.17449963e-01,  3.58536780e-01,  1.25322789e-01,  5.74094355e-02,
          2.39554001e-03, -8.60829413e-01,  3.39563429e-01,  8.69563699e-01,
         -4.70728487e-01, -4.03286994e-01, -1.17828421e-01, -6.54839635e-01,
          2.37874165e-02,  1.80120334e-01,  1.35497406e-01, -3.06149215e-01,
          2.00516414e-02, -6.48267090e-01, -2.30875947e-02, -9.88283634e-01,
          3.26673687e-01,  1.08332105e-01,  2.12138608e-01, -2.63645858e-01,
         -1.51700839e-01,  1.38495103e-01, -4.08435494e-01, -2.47935787e-01,
         -3.85777771e-01,  1.62283853e-02,  4.32449490e-01,  1.19539090e-01,
          2.81489074e-01, -2.11712345e-01, -1.01568364e-01,  6.18433177e-01,
          4.59312694e-03, -5.22594452e-01, -2.50014871e-01, -9.97673035e-01,
         -1.60245132e-02, -4.42785829e-01, -1.51318163e-01,  8.83528497e-04,
          5.02260149e-01, -1.96395531e-01, -4.50380206e-01, -2.40012724e-02,
          3.51543516e-01,  2.02494696e-01,  2.42708281e-01, -2.36003444e-01,

In [465]:
np.array([
    [w2vRecipeEmbed.wv[word] for word in word_token(ingredient_list) if word in w2vRecipeEmbed.wv]
    for ingredient_list in user_query['query']
]).shape

(1, 4, 100)

In [480]:
sentence_embedding = []
for ingredient_list in user_query['query']:
    print(ingredient_list)
    for word in word_token(ingredient_list):
        if word in w2vRecipeEmbed.wv:
            sentence_embedding.append(w2vRecipeEmbed.wv[word])
sentence_embedding = np.array(sentence_embedding)

            

spicy chicken in chinese style


In [481]:
sentence_embedding.shape

(4, 100)

In [482]:
sentence_embedding = np.mean(sentence_embedding,axis=0)
sentence_embedding

array([-0.23326047,  0.33496976,  0.12184657,  0.0884274 , -0.01974818,
       -0.81940746,  0.322254  ,  0.8167029 , -0.44284785, -0.37873313,
       -0.09166314, -0.585302  , -0.00708896,  0.2009129 ,  0.1253581 ,
       -0.2972309 , -0.01026403, -0.6005102 , -0.06147679, -0.9115356 ,
        0.31715184,  0.11122961,  0.20462346, -0.24191494, -0.12079419,
        0.12604642, -0.40185866, -0.21377105, -0.38984412,  0.01808558,
        0.38645434,  0.11759709,  0.25180292, -0.23789239, -0.09509212,
        0.5635323 ,  0.01440347, -0.4931932 , -0.22910655, -0.93126523,
       -0.02044076, -0.4235203 , -0.1513187 , -0.04191004,  0.4838162 ,
       -0.16596158, -0.4352677 ,  0.01453784,  0.3528053 ,  0.19103928,
        0.22125986, -0.21265706, -0.01991577, -0.15249373, -0.24360281,
        0.02387926,  0.15421094,  0.01440475, -0.51584685,  0.2214571 ,
        0.1192428 ,  0.04903428, -0.06019953, -0.18891767, -0.53274983,
        0.477485  ,  0.0851327 ,  0.44472727, -0.47652662,  0.71

In [472]:
mean_embedding_df = [np.mean([w2vRecipeEmbed.wv[word] for word in word_token(sentence)],axis=0) for sentence in df['TranslatedRecipeName']   ]


In [476]:
np.array(mean_embedding_df).shape

(6871, 100)

In [486]:
sentence_embedding = sentence_embedding.reshape(1,100)
sentence_embedding.shape

(1, 100)

In [484]:
sentence_embedding.shape

(100,)

In [487]:
similarity_score = cosine_similarity(sentence_embedding,mean_embedding_df)
similarity_score

array([[0.9944655 , 0.9977639 , 0.9948728 , ..., 0.99812067, 0.99942946,
        0.9764096 ]], dtype=float32)

In [488]:
df.iloc[similarity_score[0].argsort()[::-1][:10]]['TranslatedRecipeName'].tolist()

['Mizoram Style Arsa Beipenek   - Spicy Chicken Stew',
 'Spicy Goan Style Mushrooms ',
 'Asian Style Paper Wrapped Chicken ',
 'Spicy Thai Style Tofu With Quinoa ',
 'Thai Style Kai Jeow Moo Sab  - Omelette with minced Chicken',
 'Hunan Style Sweet Sour Chicken ',
 'KFC Style Crispy Chicken Popcorn ',
 'Crispy Chicken Nuggets  - KFC Style',
 'Spicy Chicken Curry  In Naga Style',
 'Himachal Style Khatta Jimikand  - Spicy Tangy Yam']

### Merging user query embeddig  and vector of userquery

In [ ]:
sentence_embedding.shape

(1, 100)

In [538]:
type(sentence_embedding)

numpy.ndarray

In [539]:
user_vector.shape


(1, 3775)

In [520]:
user_vector = user_vector.toarray()


In [ ]:
user_vector.shape[1]-sentence_embedding.shape[1]

3775

In [533]:
sentence_embedding = np.pad(sentence_embedding,pad_width=((0,0),(0,3775)), constant_values=0)

In [534]:
cobined_user_vector_embedding = np.concatenate((sentence_embedding,user_vector))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 7550 and the array at index 1 has size 3775

In [528]:
cobined_user_vector_embedding

array([[-0.23326047,  0.33496976,  0.12184657, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]])

In [530]:
combined_embeddig.shape

(6871, 7550)

In [529]:
similarity_score = cosine_similarity(cobined_user_vector_embedding,combined_embeddig)
similarity_score

ValueError: Incompatible dimension for X and Y matrices: X.shape[1] == 3775 while Y.shape[1] == 7550

In [452]:
w2vRecipeEmbed['queri']

TypeError: 'Word2Vec' object is not subscriptable

In [460]:
user_query

query
0  spicy chicken in chinese style